name: msicfree_app
description: "MsicFree - Streaming Musik Gratis"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5

  # Audio
  youtube_explode_dart: ^3.1.0
  just_audio: ^0.10.5
  # Firebase
  # HTTP & API
  http: ^1.4.0
  cached_network_image: ^3.4.1

  # Storage & Files
  path_provider: ^2.1.5
  # Navigation
  go_router: ^14.8.1

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.1
  just_audio_windows: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
